name: pagetitle
description: "A Flutter widget to dynamically update the application title."
version: 0.0.3
repository: https://github.com/hientrung/flutter_pagetitle

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
